### ISSUE TITLE
后台竞赛管理中，添加指定学员参加竞赛bug

### ISSUE THREAD

**Issue by cosmosdao** [winterant/OnlineJudge#28]
文件：app/Http/Controllers/Admin/ContestController.php

错误的行：
153行：$old_uids = DB::table('contest_users')->where('contest_id', $id)->pluck('id')->toArray();
154行：// 删除无效选手
155行：DB::table('contest_users')->where('contest_id', $id)->whereIn('id', array_diff($old_uids, $new_uids))->delete();

应该为：
153行：$old_uids = DB::table('contest_users')->where('contest_id', $id)->pluck('user_id')->toArray();
155行：DB::table('contest_users')->where('contest_id', $id)->whereIn('user_id', array_diff($old_uids, $new_uids))->delete();

**Comment by winterant** [comment]
修复 https://github.com/winterant/OnlineJudge/commit/297117daa63c4c30410fc93ba40feab07e621b6a
